version: '2'
services:
  mongo:
    image: mongo:2.6
    container_name: diff-mongo
    ports:
      - "27017:27017"
  diff:
    build: .
    container_name: diff
    image: diff:latest
    env_file: .env
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
